-- =========================================================================
-- 1. POLICY ID SEQUENCE SETUP
-- =========================================================================
CREATE SEQUENCE IF NOT EXISTS policy_id_seq START WITH 1 INCREMENT BY 1;

-- =========================================================================
-- 2. POLICIES TABLE SETUP
-- =========================================================================
CREATE TABLE IF NOT EXISTS policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_id VARCHAR(50) NOT NULL, -- Standard VARCHAR, accepts duplicates across versions
    document_id BIGINT, 
    coverage_amount INTEGER, 
    is_latest BOOLEAN NOT NULL DEFAULT TRUE, 
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(500), 
    policy_type VARCHAR(50) NOT NULL CHECK (policy_type IN ('HEALTH','LIFE','HOME','VEHICLE')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE','TERMINATED')),
    coverage_duration BYTEA, 
    premiums_duration BYTEA, 
    
    PRIMARY KEY (id)
);

-- =========================================================================
-- 3. B-TREE PERFORMANCE TUNING INDEXES (NON-UNIQUE)
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_policies_document_id ON policies(document_id);
CREATE INDEX IF NOT EXISTS idx_policies_policy_id ON policies(policy_id);