-- =========================================================================
-- 1. CLEAN SLATE RUN: DROP EXISTING CONSTRAINTS AND TABLES 
-- =========================================================================
ALTER TABLE IF EXISTS policies             DROP CONSTRAINT IF EXISTS FKiywr22mjeeouexymef9sc0yl0;
ALTER TABLE IF EXISTS policy_subscriptions DROP CONSTRAINT IF EXISTS FKc54atnptlh61n5ge5uc4vk054;
ALTER TABLE IF EXISTS premium_payments     DROP CONSTRAINT IF EXISTS FKt5xmrkx91tyicn4nwnqglf5tj;
ALTER TABLE IF EXISTS proofs               DROP CONSTRAINT IF EXISTS FKkgv7kdrdqwbwacrtfjw1qh646;
ALTER TABLE IF EXISTS proofs               DROP CONSTRAINT IF EXISTS FKd6u56mkygtku8jfn1bdlvpd9j;

DROP TABLE IF EXISTS claims cascade;
DROP TABLE IF EXISTS documents cascade;
DROP TABLE IF EXISTS policies cascade;
DROP TABLE IF EXISTS policy_subscriptions cascade;
DROP TABLE IF EXISTS premium_payments cascade;
DROP TABLE IF EXISTS proofs cascade;

-- =========================================================================
-- 2. CREATE SCHEMAS WITH INDEX-READY PERFORMANCE AND STRONGER TYPES
-- =========================================================================

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id UUID NOT NULL, 
    deleted BOOLEAN DEFAULT FALSE, 
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP, 
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(512) NOT NULL, 
    PRIMARY KEY (id)
);

CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id BIGINT UNIQUE,
    coverage_amount INTEGER, 
    is_latest BOOLEAN NOT NULL DEFAULT TRUE, 
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(500), 
    policy_type VARCHAR(50) NOT NULL CHECK (policy_type IN ('HEALTH','LIFE','HOME','VEHICLE')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE','TERMINATED')),
    coverage_duration BYTEA, 
    premiums_duration BYTEA, 
    
    -- Computes 'POLICY-0001' to 'POLICY-9999', then scales organically
    policy_id VARCHAR(50) GENERATED ALWAYS AS (
        CASE 
            WHEN id <= 9999 THEN 'POLICY-' || LPAD(id::TEXT, 4, '0')
            ELSE 'POLICY-' || id::TEXT
        END
    ) STORED UNIQUE,
    
    PRIMARY KEY (id)
);

CREATE TABLE claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cust_id UUID NOT NULL, 
    agent_id UUID,
    resolver_id UUID,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    agent_name VARCHAR(150),
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('INITIATED','ASSIGNED','PENDING','APPROVED','REJECTED')),
    
    -- Computes 'CLAIM-0001' to 'CLAIM-9999', then scales organically
    claim_id VARCHAR(50) GENERATED ALWAYS AS (
        CASE 
            WHEN id <= 9999 THEN 'CLAIM-' || LPAD(id::TEXT, 4, '0')
            ELSE 'CLAIM-' || id::TEXT
        END
    ) STORED UNIQUE,
    
    PRIMARY KEY (id)
);

CREATE TABLE policy_subscriptions (
    id UUID NOT NULL, 
    policy_id BIGINT NOT NULL,
    cust_id UUID NOT NULL,
    agent_id UUID,
    start_date DATE,
    end_date DATE,
    expiry DATE,
    acceptance_time TIMESTAMP(6),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE','PENDING','EXPIRED')),
    PRIMARY KEY (id)
);

CREATE TABLE premium_payments (
    id UUID NOT NULL, 
    subscription_id UUID NOT NULL,
    cust_id UUID NOT NULL,
    amount_payed INTEGER,
    premium_amount INTEGER,
    due_date DATE NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    payment_time TIMESTAMP(6),
    method VARCHAR(50),
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING','PAID','OVERDUE')),
    PRIMARY KEY (id)
);

CREATE TABLE proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    claim_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT unique_claim_proof_document UNIQUE (claim_id, document_id)
);

-- =========================================================================
-- 3. APPLY FOREIGN KEY CONSTRAINTS
-- =========================================================================
ALTER TABLE IF EXISTS policies             ADD CONSTRAINT FKiywr22mjeeouexymef9sc0yl0 FOREIGN KEY (document_id) REFERENCES documents(id);
ALTER TABLE IF EXISTS policy_subscriptions ADD CONSTRAINT FKc54atnptlh61n5ge5uc4vk054 FOREIGN KEY (policy_id) REFERENCES policies(id);
ALTER TABLE IF EXISTS premium_payments     ADD CONSTRAINT FKt5xmrkx91tyicn4nwnqglf5tj FOREIGN KEY (subscription_id) REFERENCES policy_subscriptions(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS proofs               ADD CONSTRAINT FKkgv7kdrdqwbwacrtfjw1qh646 FOREIGN KEY (claim_id) REFERENCES claims(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS proofs               ADD CONSTRAINT FKd6u56mkygtku8jfn1bdlvpd9j FOREIGN KEY (document_id) REFERENCES documents(id);

-- =========================================================================
-- 4. PERFORMANCE TUNING INDEXES (OPTIMIZED FOR MULTI-TENANT FILTER SPEED)
-- =========================================================================
CREATE INDEX idx_claims_cust_id ON claims(cust_id);
CREATE INDEX idx_claims_agent_id ON claims(agent_id);
CREATE INDEX idx_policy_subscriptions_cust_id ON policy_subscriptions(cust_id);
CREATE INDEX idx_policy_subscriptions_policy_id ON policy_subscriptions(policy_id);
CREATE INDEX idx_premium_payments_subscription_id ON premium_payments(subscription_id);
CREATE INDEX idx_premium_payments_cust_id ON premium_payments(cust_id);
CREATE INDEX idx_documents_owner_id ON documents(owner_id);
