CREATE TABLE IF NOT EXISTS policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id BIGINT, 
    coverage_amount INTEGER, 
    is_latest BOOLEAN NOT NULL DEFAULT TRUE, 
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(500), 
    policy_type VARCHAR(50) NOT NULL CHECK (policy_type IN ('HEALTH','LIFE','HOME','VEHICLE')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE','TERMINATED')),
    coverage_duration BYTEA, 
    premiums_duration BYTEA, 
    
    policy_id VARCHAR(50) GENERATED ALWAYS AS (
        CASE 
            WHEN id <= 9999 THEN 'POLICY-' || LPAD(id::TEXT, 4, '0')
            ELSE 'POLICY-' || id::TEXT
        END
    ) STORED UNIQUE,
    
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_policies_document_id ON policies(document_id);
