spring:
    application:
        name: identityservice
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ims_identity
        username: admin
        password: admin
    jpa:
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
    jwt:
        secret: 1234567890123456789012345678901234567890123456789012345678901234
        access-token-expiration: 900000      # 15 mins
        refresh-token-expiration: 604800000  # 7 days