spring:
    application:
        name: IMS-IDENTITY
    config:
        import: configserver:http://localhost:8888
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
        username: admin
        password: admin
    jpa:
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
    jwt:
        secret: 1234567890123456789012345678901234567890123456789012345678901234
        access-token-expiration: 900000      # 15 mins
        refresh-token-expiration: 604800000  # 7 days