-- =========================================================================
-- 1. CLAIM ID SEQUENCE SETUP
-- =========================================================================
CREATE SEQUENCE IF NOT EXISTS claim_id_seq START WITH 1 INCREMENT BY 1;

-- =========================================================================
-- 2. CLAIMS TABLE SETUP
-- =========================================================================
CREATE TABLE IF NOT EXISTS claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    claim_id VARCHAR(50) NOT NULL,
    cust_id UUID NOT NULL,
    agent_id UUID,
    resolver_id UUID,
    subscription_id UUID,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    agent_name VARCHAR(150),
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('INITIATED','ASSIGNED','PENDING','APPROVED','REJECTED')),
    
    PRIMARY KEY (id)
);

-- Ensure claim_id remains unique across all claim records
CREATE UNIQUE INDEX IF NOT EXISTS idx_claims_claim_id ON claims(claim_id);

-- =========================================================================
-- 3. PROOFS TABLE SETUP
-- =========================================================================
CREATE TABLE IF NOT EXISTS proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    claim_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    
    CONSTRAINT unique_claim_proof_link UNIQUE (claim_id, document_id)
);

-- =========================================================================
-- 4. FOREIGN KEY RELATIONSHIPS
-- =========================================================================
ALTER TABLE proofs 
    DROP CONSTRAINT IF EXISTS FKkgv7kdrdqwbwacrtfjw1qh646,
    ADD CONSTRAINT FKkgv7kdrdqwbwacrtfjw1qh646 
        FOREIGN KEY (claim_id) REFERENCES claims(id) ON DELETE CASCADE;

-- =========================================================================
-- 5. B-TREE PERFORMANCE TUNING INDEXES
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_claims_cust_id ON claims(cust_id);
CREATE INDEX IF NOT EXISTS idx_claims_subscription_id ON claims(subscription_id);
CREATE INDEX IF NOT EXISTS idx_proofs_claim_id ON proofs(claim_id);
CREATE INDEX IF NOT EXISTS idx_proofs_document_id ON proofs(document_id);