-- =========================================================================
-- 1. CLAIMS TABLE SETUP
-- =========================================================================
CREATE TABLE IF NOT EXISTS claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cust_id UUID NOT NULL,
    agent_id UUID,
    resolver_id UUID,
    subscription_id UUID,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    agent_name VARCHAR(150),
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('INITIATED','ASSIGNED','PENDING','APPROVED','REJECTED')),
    
    claim_id VARCHAR(50) GENERATED ALWAYS AS (
        CASE 
            WHEN id <= 9999 THEN 'CLAIM-' || LPAD(id::TEXT, 4, '0')
            ELSE 'CLAIM-' || id::TEXT
        END
    ) STORED UNIQUE,
    
    PRIMARY KEY (id)
);

-- =========================================================================
-- 2. PROOFS TABLE SETUP
-- =========================================================================
CREATE TABLE IF NOT EXISTS proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    claim_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    
    CONSTRAINT unique_claim_proof_link UNIQUE (claim_id, document_id)
);

-- =========================================================================
-- 3. FOREIGN KEY RELATIONSHIPS
-- =========================================================================
ALTER TABLE proofs 
    DROP CONSTRAINT IF EXISTS FKkgv7kdrdqwbwacrtfjw1qh646,
    ADD CONSTRAINT FKkgv7kdrdqwbwacrtfjw1qh646 
        FOREIGN KEY (claim_id) REFERENCES claims(id) ON DELETE CASCADE;

-- =========================================================================
-- 4. B-TREE PERFORMANCE TUNING INDEXES
-- =========================================================================
-- Explicit indexes over lookup paths and keys to accelerate analytical search criteria
CREATE INDEX IF NOT EXISTS idx_claims_cust_id ON claims(cust_id);
CREATE INDEX IF NOT EXISTS idx_claims_subscription_id ON claims(subscription_id);
CREATE INDEX IF NOT EXISTS idx_proofs_claim_id ON proofs(claim_id);
CREATE INDEX IF NOT EXISTS idx_proofs_document_id ON proofs(document_id);
